## Wokwi project config for ESP32 DevKit + SSD1306 I2C OLED

[wokwi]
version = 1
firmware = "../esp-idf/build/m365_dash_idf.bin"   # or "build/M365.ino.bin"
elf = "../esp-idf/build/m365_dash_idf.elf"   # or "build/M365.ino.bin"

[arduino]
fqbn = "esp32:esp32:esp32c3"
sketch = "../M365/M365.ino"
defines = ["SIM_MODE"]
