## Wokwi project config for ESP32 DevKit + SSD1306 I2C OLED

[wokwi]
version = 1
firmware = "../build-local/ESP32-C3-Dev-SIM/M365.ino.bin"   # or "build/M365.ino.bin"
elf      = "../build-local/ESP32-C3-Dev-SIM/M365.ino.elf"   # optional but speeds things up

[arduino]
fqbn = "esp32:esp32:esp32c3"
sketch = "../M365/M365.ino"
defines = ["SIM_MODE"]
