name: ESP-IDF ESP32-C3 Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'
  pull_request:
  workflow_dispatch:
    inputs:
      makeRelease:
        description: 'Create GitHub Release (manual runs)'
        required: false
        default: 'false'
      tag_name:
        description: 'Tag name for manual release (empty = manual-<sha>)'
        required: false
        default: ''
      release_name:
        description: 'Release name (optional)'
        required: false
        default: ''
      prerelease:
        description: 'Mark as prerelease (manual runs)'
        required: false
        default: 'true'
      draft:
        description: 'Mark as draft (manual runs)'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  build-idf:
    runs-on: ubuntu-latest
    env:
      IDF_TARGET: esp32c3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initialize submodules
        run: |
          set -e
          git submodule sync --recursive
          git submodule update --init --recursive --depth 1
          echo "Listing component directories after submodule init:";
          ls -1 esp-idf/components || true

      - name: Fallback clone missing u8g2 components
        run: |
          set -e
          NEED_CLONE=0
          if [ ! -d esp-idf/components/u8g2 ]; then
            echo "u8g2 submodule missing; cloning shallow copy.";
            git clone --depth 1 https://github.com/olikraus/u8g2.git esp-idf/components/u8g2
            NEED_CLONE=1
          fi
          if [ ! -d esp-idf/components/u8g2-hal-esp-idf ]; then
            echo "u8g2-hal-esp-idf submodule missing; cloning shallow copy.";
            git clone --depth 1 https://github.com/mkfrey/u8g2-hal-esp-idf.git esp-idf/components/u8g2-hal-esp-idf
            NEED_CLONE=1
          fi
          if [ "$NEED_CLONE" = 1 ]; then
            echo "Post-clone component directories:";
            ls -1 esp-idf/components
          fi

      - name: Setup ESP-IDF (manual)
        run: |
          git clone --depth 1 --branch v5.2.2 https://github.com/espressif/esp-idf.git framework
          cd framework
          ./install.sh esp32c3
          echo "FRAMEWORK_DIR=$PWD" >> $GITHUB_ENV
          # Do not write 'source' lines to GITHUB_ENV (invalid); we will source explicitly in each step.

      - name: Show IDF version
        run: |
          set -e
          . "$FRAMEWORK_DIR/export.sh"
          idf.py --version

      - name: Build (esp32c3)
        run: |
          set -e
          . "$FRAMEWORK_DIR/export.sh"
          chmod +x scripts/build_local.sh
          # Use project script (already sets target) but force target before to be explicit
          IDF_PATH="$FRAMEWORK_DIR" idf.py -C esp-idf set-target esp32c3
          IDF_PATH="$FRAMEWORK_DIR" scripts/build_local.sh
          test -f esp-idf/build/m365_dash_idf.bin
      - name: List discovered components
        run: |
          find esp-idf/components -maxdepth 1 -type d -print
          echo "---- CMake config log snippet ----" || true
          grep -i "u8g2" -R esp-idf/build/CMakeCache.txt || true

      - name: Collect artifacts
        run: |
          set -e
          mkdir -p ci-artifacts
          cp -v esp-idf/build/m365_dash_idf.bin ci-artifacts/
          cp -v esp-idf/build/bootloader/bootloader.bin ci-artifacts/
          cp -v esp-idf/build/partition_table/partition-table.bin ci-artifacts/
          cp -v esp-idf/build/m365_dash_idf.elf ci-artifacts/
          ls -l ci-artifacts

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32c3-firmware
          path: ci-artifacts/*
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build-idf
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.makeRelease == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: esp32c3-firmware
          path: dist

      - name: Compute release metadata
        id: meta
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "push" ] && [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF_NAME}"
            NAME="${GITHUB_REF_NAME}"
            PRERELEASE="false"
            DRAFT="false"
          else
            TAG="${{ inputs.tag_name }}"
            [ -z "$TAG" ] && TAG="manual-${GITHUB_SHA}"
            NAME="${{ inputs.release_name }}"
            PRERELEASE="${{ inputs.prerelease }}"
            [ -z "$PRERELEASE" ] && PRERELEASE="true"
            DRAFT="${{ inputs.draft }}"
            [ -z "$DRAFT" ] && DRAFT="false"
          fi
          echo "rel_tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "rel_name=$NAME" >> "$GITHUB_OUTPUT"
          echo "rel_prerelease=$PRERELEASE" >> "$GITHUB_OUTPUT"
          echo "rel_draft=$DRAFT" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.rel_tag }}
          name: ${{ steps.meta.outputs.rel_name }}
          prerelease: ${{ steps.meta.outputs.rel_prerelease }}
          draft: ${{ steps.meta.outputs.rel_draft }}
          files: |
            dist/*.bin
            dist/*.elf
